use_frameworks!

platform :ios, '8.0'

target 'WKTabbarController_Example' do
  pod 'WKTabbarController', :path => '../'

  target 'WKTabbarController_Tests' do
    inherit! :search_paths

  end
  
  pod 'AxcAE_TabBar'
end
